package com.example.emergencytranslator.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7AF8DB)
val md_theme_light_onPrimaryContainer = Color(0xFF00201A)
val md_theme_light_secondary = Color(0xFF2A6B29)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFADF4A1)
val md_theme_light_onSecondaryContainer = Color(0xFF002202)
val md_theme_light_tertiary = Color(0xFFAE3200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBD0)
val md_theme_light_onTertiaryContainer = Color(0xFF3A0B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFA)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7975)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inversePrimary = Color(0xFF5ADBBF)
val md_theme_light_surfaceTint = Color(0xFF006B5A)
val md_theme_light_outlineVariant = Color(0xFFBFC9C4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5ADBBF)
val md_theme_dark_onPrimary = Color(0xFF00382E)
val md_theme_dark_primaryContainer = Color(0xFF005143)
val md_theme_dark_onPrimaryContainer = Color(0xFF7AF8DB)
val md_theme_dark_secondary = Color(0xFF92D787)
val md_theme_dark_onSecondary = Color(0xFF003906)
val md_theme_dark_secondaryContainer = Color(0xFF0D5213)
val md_theme_dark_onSecondaryContainer = Color(0xFFADF4A1)
val md_theme_dark_tertiary = Color(0xFFFFB59E)
val md_theme_dark_onTertiary = Color(0xFF5E1700)
val md_theme_dark_tertiaryContainer = Color(0xFF852400)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBD0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E0)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E0)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C4)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E0)
val md_theme_dark_inversePrimary = Color(0xFF006B5A)
val md_theme_dark_surfaceTint = Color(0xFF5ADBBF)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)


